import {
   StAlertsDemoModule,
   StBreadcrumbsDemoModule,
   StButtonDemoModule,
   StDropdownDemoModule,
   StDropdownMenuDemoModule,
   StFormDemoModule,
   StHelpDemoModule,
   StInfoBoxDemoModule,
   StInputDemoModule,
   StItemListDemoModule,
   StModalDemoModule,
   StPageTitleDemoModule,
   StPaginationDemoModule,
   StSearchDemoModule,
   StSelectDemoModule,
   StSwitchDemoModule,
   StTipDemoModule,
   StTooltipDemoModule,
   StTreeDemoModule,
   StTwoListSelectionDemoModule
} from '@stratio/egeo-demo';

export const DECLARATIONS: any[] = [
   StAlertsDemoModule,
   StBreadcrumbsDemoModule,
   StButtonDemoModule,
   StDropdownDemoModule,
   StDropdownMenuDemoModule,
   StFormDemoModule,
   StHelpDemoModule,
   StInfoBoxDemoModule,
   StInputDemoModule,
   StItemListDemoModule,
   StModalDemoModule,
   StPageTitleDemoModule,
   StPaginationDemoModule,
   StSearchDemoModule,
   StSelectDemoModule,
   StSwitchDemoModule,
   StTipDemoModule,
   StTooltipDemoModule,
   StTreeDemoModule,
   StTwoListSelectionDemoModule
];
